### ISSUE TITLE
[1.19.2] Crash when creating/joining world: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Ricenami** [CircuitLord/ReactiveMusic#1]
Hi, me and my group of friends play on our own custom mc server, and we saw your mod and we all absolutely love it! The first thing I did was test the mod in singleplayer and I came across this crash:

```
java.lang.NoSuchMethodError: 'net.minecraft.class_1297 net.minecraft.class_746.method_49694()'
	at circuitlord.bettermusic.SongPicker.tickEventMap(SongPicker.java:55)
	at circuitlord.bettermusic.BetterMusic.tick(BetterMusic.java:78)
	at net.minecraft.class_310.handler$zin000$adventureredefined$bettermusic$tick(class_310.java:6469)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
Here's the full crash log:
[crash-2023-09-03_15.31.09-client.txt](https://github.com/CircuitLord/AdventureRedefined/files/14005383/crash-2023-09-03_15.31.09-client.txt)

We are on fabric 1.19.2, running fabric loader 15.6. We have a lot of mods, but we don't have any issues or crashes while playing. AdventureRedefined is the only new mod that was added into our modpack. Hopefully there is a workaround for this issue because me and my friends would really love to use your mod, cheers!

**Comment by CircuitLord** [comment]
Heyo sorry I missed responding to this but the mod isn't actually compatible with 1.19.2 and lower, Mojang changed how the biome stuff worked in 1.19 so unfortunately i'd have to re-write for older versions, since I have limited time I'll probably stick to just maintaining the most recent versions
