### ISSUE TITLE
Incompatible with other implementations of snakeyaml

### ISSUE THREAD

**Issue by Stella-Zephyr** [CircuitLord/ReactiveMusic#38]
OS: Arch Linux
Mod Loader: Fabric Loader 0.16.9
Minecraft Version: 1.21.1
Launcher: Prism Launcher
Mod Version: 1.0.0

```
Time: 2024-12-30 18:55:14
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'reactivemusic' at 'circuitlord.reactivemusic.ReactiveMusic'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchFieldError: Class org.yaml.snakeyaml.constructor.Constructor does not have member field 'java.lang.String errorString'
	at knot//circuitlord.reactivemusic.RMSongpackLoader.loadSongpack(RMSongpackLoader.java:158)
	at knot//circuitlord.reactivemusic.RMSongpackLoader.fetchAvailableSongpacks(RMSongpackLoader.java:96)
	at knot//circuitlord.reactivemusic.ReactiveMusic.onInitialize(ReactiveMusic.java:104)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
Mixins in Stacktrace:
	net.minecraft.class_310:
		io.github.thecsdev.tcdcommons.client.mixin.events.MixinMinecraftClient (tcdcommons.client.mixin.events.json)
		net.irisshaders.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		fi.dy.masa.litematica.mixin.MixinMinecraftClient (mixins.litematica.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		mod.crend.libbamboo.mixin.MinecraftClientMixin (libbamboo-common.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.core.MixinMinecraftClient (immediatelyfast-common.mixins.json)
		de.keksuccino.fancymenu.mixin.mixins.common.client.IMixinMinecraft (fancymenu.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.core.MixinMinecraftClient (sodium-extra.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.common.client.IMixinMinecraft (drippyloadingscreen.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		de.kb1000.notelemetry.mixin.MinecraftClientMixin (no-telemetry.mixins.json)
		fuzs.pickupnotifier.mixin.client.MinecraftMixin (pickupnotifier.common.mixins.json)
		bettercommandblockui.mixin.MinecraftClientMixin (bettercommandblockui.mixins.json)
		fuzs.puzzleslib.fabric.mixin.client.MinecraftFabricMixin (puzzleslib.fabric.mixins.json)
		foundationgames.enhancedblockentities.mixin.MinecraftClientMixin (enhancedblockentities.mixins.json)
		com.aizistral.nochatreports.fabric.mixins.client.MixinMinecraft (mixins/fabric/nochatreports-fabric.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl.mixins.json)
		com.anthonyhilyard.prism.mixin.MinecraftMixin (prism.mixins.json)
		com.sonicether.soundphysics.mixin.MinecraftMixin (sound_physics_remastered.mixins.json)
		net.irisshaders.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientMixin (fastquit.mixins.json)
		eu.midnightdust.blur.mixin.MixinMinecraftClient (blur.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		dynamic_fps.impl.mixin.MinecraftMixin (dynamic_fps-common.mixins.json)
		net.xolt.freecam.mixins.MinecraftMixin (freecam-common.mixins.json)
		ca.fxco.moreculling.mixin.blockstates.Minecraft_loadBlocksMixin (moreculling.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc46766.MinecraftMixin (debugify.client.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		codes.atomys.advr.mixin.MinecraftClientMixin (advancements_reloaded.mixins.json)
		nl.enjarai.cicada.mixin.EntityRenderStateMixin (cicada.mixins.json)
		mod.crend.libbamboo.mixin.MinecraftClientAccessor (libbamboo-common.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		com.ishland.vmp.mixins.timesource.MixinMinecraftClient (vmp.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		traben.entity_model_features.mixin.accessor.MinecraftClientAccessor (entity_model_features-common.mixins.json)
		dev.imb11.sounds.mixin.ui.ScreenSoundEffect (sounds.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.fabric.mixins.json)
		com.natamus.collective.fabric.mixin.MinecraftMixin (collective_fabric.mixins.json)
		xaero.map.mixin.MixinMinecraftClient (xaeroworldmap.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinMinecraft (konkrete.mixins.json)
		com.github.exopandora.shouldersurfing.fabric.mixins.MixinMinecraft (shouldersurfing.fabric.mixins.json)
		net.caffeinemc.mods.sodium.mixin.core.MinecraftMixin (sodium-common.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		com.minelittlepony.common.mixin.MixinMinecraftClient (kirin.mixin.json)
		com.minenash.seamless_loading_screen.mixin.MinecraftClientMixin (seamless_loading_screen-common.mixins.json)
		com.aizistral.nochatreports.common.mixins.client.MixinMinecraft (mixins/common/nochatreports.mixins.json)
		dev.tr7zw.notenoughanimations.mixins.LivingRenderStateMixin (notenoughanimations.mixins.json)
		net.darkhax.bookshelf.common.mixin.access.client.AccessorMinecraft (bookshelf.mixins.json)
		traben.entity_model_features.mixin.MixinResourceReloadEnd (entity_model_features-common.mixins.json)
		de.dafuqs.disableaccessibilityscreen.mixin.MinecraftClientMixin (disableaccessibilityscreen.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		dev.hephaestus.atmosfera.mixin.MinecraftClientMixin (atmosfera.mixins.json)
		com.corosus.watut.mixin.client.MinecraftTick (watut_fabric.mixins.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		org.anti_ad.mc.ipnext.mixin.MixinMinecraftClient (mixins.ipnext.json)
		traben.entity_model_features.mixin.MixinResourceReloadStart (entity_model_features-common.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		xaero.common.mixin.MixinMinecraftClient (xaerohud.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientAccessor (fastquit.mixins.json)
		net.irisshaders.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		circuitlord.reactivemusic.mixin.MinecraftClientMixin (reactivemusic.mixins.json)
		org.ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.fabric.mixins.json)
		dev.isxander.zoomify.mixins.hooks.MinecraftClientMixin (zoomify.mixins.json)
		me.polishkrowa.ctrlq.mixin.MixinMinecraftClient (ctrl-q.mixins.json)
		ca.fxco.moreculling.mixin.Minecraft_managersMixin (moreculling.mixins.json)
		de.keksuccino.fancymenu.mixin.mixins.common.client.MixinMinecraft (fancymenu.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		net.mehvahdjukaar.polytone.mixins.MinecraftMixin (polytone-common.mixins.json)
		fi.dy.masa.litematica.mixin.MixinMinecraftClient_easyPlace (mixins.litematica.json)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		link.infra.screenshotclipboard.common.mixin.AWTHackMixin (screenshotclipboard-common.mixins.json)


-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.12.7-arch1-1
	Java Version: 21.0.5, Arch Linux
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
	Memory: 525870752 bytes (501 MiB) / 775946240 bytes (740 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 20306.09
	Virtual memory used (MiB): 7100.80
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 3295.07
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 3216.10, total: 3922.10
	Space in storage for workdir (MiB): available: 22125.00, total: 234921.55
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.6.8
		advancements_reloaded: Advancements Reloaded 0.6.1
		architectury: Architectury 13.0.8
		atmosfera: Atmosfera 2.1.0+mc1.21
		autohud: Auto HUD 8.0
		balm-fabric: Balm 21.0.22
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		betterbeds: Better Beds 1.4.0
		bettercommandblockui: BetterCommandBlockUI 0.5.2a
		betterf3: BetterF3 11.0.3
		bettermounthud: Better Mount HUD 1.2.4
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 3.13.4+fabric-1.21
		blur: Blur+ (Fabric) 5.0.0
			midnightlib: MidnightLib 1.6.3
		bookshelf: Bookshelf 21.1.28
		brrp_v1: Better Runtime Resource Pack (BRRP) v1 1.0.4
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		chat_heads: Chat Heads 0.13.7
		chatanimation: ChatAnimation 1.0.6
		chatpatches: Chat Patches 211.6.9
		cicada: CICADA 0.10.2+1.21-1.21.1
		citresewn: CIT Resewn 1.2.2+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.2+1.21
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		collective: Collective 7.87
		continuity: Continuity 3.0.0+1.21
		controlling: Controlling 19.0.3
		coroutil: CoroUtil 1.21.0-1.3.7
		creativecore: CreativeCore 2.12.23
			net_neoforged_bus: bus 7.2.0
		ctrl-q: Ctrl Q 1.9
		debugify: Debugify 1.21.1+1.0
		disableaccessibilityscreen: DisableAccessibilityScreen 1.0.1
		do_a_barrel_roll: Do a Barrel Roll 3.7.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		drippyloadingscreen: Drippy Loading Screen 3.0.8
		durabilitytooltip: Durability Tooltip 1.1.5
		dynamic_fps: Dynamic FPS 3.7.7
			net_lostluma_battery: battery 1.3.0
		dynamiccrosshair: Dynamic Crosshair 9.3
			dynamiccrosshair-api: DynamicCrosshair API 1.1
			libbamboo: LibBamboo 2.2
		enchdesc: EnchantmentDescriptions 21.1.5
		enhanced_attack_indicator: Enhanced Attack Indicator 1.1.0+1.21
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		enhancedvisuals: EnhancedVisuals 1.8.14
		entity_model_features: Entity Model Features 2.4.1
		entity_texture_features: Entity Texture Features 6.2.9
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.2
		explosiveenhancement: Explosive Enhancement 1.3.2-1.21-1.21.1
		fabric-api: Fabric API 0.114.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.31+d527f9fd19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.25+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.14+248df81c19
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+c24bd99419
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fallingleaves: Falling Leaves 1.16.4
		fancymenu: FancyMenu 3.3.2
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		fastquit: FastQuit 3.0.0+1.20.6
		fbp: FancyBlockParticles 21.1.2.0
		ferritecore: FerriteCore 7.0.2-hotfix
		feytweaks: FeyTweaks 1.21-1.2.8
		firstperson: FirstPerson 2.4.8
		forgeconfigapiport: Forge Config API Port 21.1.3
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		freecam: Freecam (Modrinth Edition) 1.3.0+mc1.21
		fsb-interop: FabricSkyBoxes Interop 1.4.0+mc1.21-build.54
		geckolib: GeckoLib 4 4.7.3
		highlighter: Highlighter 1.1.11
		holdthatchunk: Hold That Chunk 2.1.0
		iceberg: Iceberg 1.2.7
		immediatelyfast: ImmediatelyFast 1.3.3+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		inventoryprofilesnext: Inventory Profiles Next 2.1.0
		iris: Iris 1.8.1+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemborders: Item Borders 1.2.5
		jade: Jade 15.9.2+fabric
		java: OpenJDK 64-Bit Server VM 21
		konkrete: Konkrete 1.9.9
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lambdynlights: LambDynamicLights 3.1.4+1.21.1
			pride: Pride Lib 1.2.1+1.21
			spruceui: SpruceUI 5.1.0+1.21
		languagereload: Language Reload 1.7.2+1.21.1
		legendarytooltips: Legendary Tooltips 1.4.11
		libipn: libIPN 6.2.0
		litematica: Litematica 0.19.54
		litematicawand: litematicaWand 1.0+1.21.1
		lithium: Lithium 0.14.3-snapshot+mc1.21.1-build.92
		make_bubbles_pop: Make Bubbles Pop 0.3.0-fabric
		malilib: MaLiLib 0.21.6
		melody: Melody 1.0.10
		minecraft: Minecraft 1.21.1
		mixintrace: MixinTrace 1.1.1+1.17
		modelfix: Model Gap Fix 1.21-1.6
		modmenu: Mod Menu 11.0.3
		moreculling: More Culling 1.0.3
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		mousetweaks: Mouse Tweaks 2.26
		mru: Mineblock's Repeated Utilities 1.0.7+1.21+fabric
		narrus_yeetus_no_error: Narrus Yeetus no error 1.1.0
		nerb: Not Enough Recipe Book 0.4.1
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		no-telemetry: No Telemetry 1.8.0
		nochatreports: No Chat Reports 1.21.1-v2.9.1
		notenoughanimations: NotEnoughAnimations 1.9.0
		octolib: OctoLib 0.5.0.1
			org_yaml_snakeyaml: snakeyaml 2.2
		owo: oωo 0.12.15+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		particular: Particular 1.1.1+1.21
		pickupnotifier: Pick Up Notifier 21.1.0
		placeholder-api: Placeholder API 2.4.1+1.21
		playeranimator: Player Animator 2.0.1+1.21.1
		polytone: Polytone 1.21-3.1.3
			net_objecthunter_exp4j: exp4j 0.4.8
		presencefootsteps: Presence Footsteps 1.10.3+1.21
			kirin: Kirin UI 1.20.0+1.21
		prickle: PrickleMC 21.1.6
		prism: root project 'Prism' 1.0.9
		puzzle: Puzzle 2.0.1
		puzzleslib: Puzzles Lib 21.1.24
		reactivemusic: Reactive Music 1.0.0+1.21
		reeses-sodium-options: Reese's Sodium Options 1.8.0+mc1.21.3
		roughlyenoughitems: Roughly Enough Items 16.0.788
			error_notifier: Error Notifier 1.0.11
		screenshotclipboard: Screenshot to Clipboard 1.0.10
		seamless_loading_screen: Seamless Loading Screen 2.2.1+1.21
		searchables: Searchables 1.0.2
		seasons: Fabric Seasons 2.4.2-BETA+1.21
		seriousplayeranimations: Serious Player Animations 1.2.0
		shouldersurfing: Shoulder Surfing Reloaded 4.6.4
		showmeyourskin: Show Me Your Skin! 1.11.3+1.21
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		shulkerboxtooltip: Shulker Box Tooltip 5.1.2+1.21.1
		skinlayers3d: 3d-Skin-Layers 1.7.4
		sodium: Sodium 0.6.5+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.8
		sounds: Sounds 2.3.0+1.21+fabric
			mixinextras: MixinExtras 0.5.0-beta.2
		status-effect-bars: Status Effect Bars 1.0.6
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		tcdcommons: TCD Commons API 3.12.5+fabric-1.21
		tooltipfix: ToolTip Fix 1.1.1-1.20
		vmp: Very Many Players 0.2.0+beta.7.169+1.21.1
			com_ibm_async_asyncutil: asyncutil 0.1.0
		wakes: Wakes 0.3.0+1.21.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 2.0.0
		watut: What Are They Up To 1.21.0-1.1.3
		xaerominimap: Xaero's Minimap 24.7.1
		xaeroworldmap: Xaero's World Map 1.39.2
		yeetusexperimentus: Yeetus Experimentus 87.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.14.2+1.21.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.2
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_MX
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
```

**Comment by Stella-Zephyr** [comment]
It seems the program is trying to look for a field that is private or does not exist.

**Comment by Stella-Zephyr** [comment]
UPDATE: Mod is incompatible with other mods that have an implementation of snakeyaml. Current suspect is OctoLib, further research is advised on this front.

**Comment by CircuitLord** [comment]
fixed in https://github.com/CircuitLord/ReactiveMusic/commit/323b0f8e453e2dab87a3dca2b304cedb6702e84a, thanks for the report!
